/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminOrder { 'orders' : Array<Order>, 'user' : Principal }
export interface BkashConfig {
  'isSandbox' : boolean,
  'username' : string,
  'password' : string,
  'appKey' : string,
  'appSecret' : string,
}
export interface CartItem { 'productId' : string, 'quantity' : bigint }
export type Category = { 'pharmacy' : null } |
  { 'books' : null } |
  { 'fashion' : null } |
  { 'electronics' : null };
export interface DashboardStats {
  'totalProducts' : bigint,
  'totalOrders' : bigint,
  'outOfStockProducts' : bigint,
  'totalRevenue' : bigint,
}
export type ExternalBlob = Uint8Array;
export interface NagadConfig {
  'isSandbox' : boolean,
  'merchantID' : string,
  'merchantPrivateKey' : string,
}
export interface Order {
  'status' : string,
  'total' : bigint,
  'paymentMethod' : string,
  'createdAt' : bigint,
  'orderId' : string,
  'items' : Array<CartItem>,
}
export interface OrderStatus {
  'status' : string,
  'user' : Principal,
  'orderId' : string,
}
export interface Product {
  'id' : string,
  'inStock' : boolean,
  'name' : string,
  'description' : string,
  'imageUrl' : [] | [string],
  'category' : Category,
  'requiresPrescription' : boolean,
  'price' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[Product], undefined>,
  'addToCart' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createBkashPayment' : ActorMethod<[string, string, string], string>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'executeBkashPayment' : ActorMethod<[string, string], string>,
  'getAllOrders' : ActorMethod<[], Array<AdminOrder>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Array<CartItem>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getMyOrders' : ActorMethod<[], Array<Order>>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantBkashToken' : ActorMethod<[], string>,
  'hasPrescription' : ActorMethod<[string, string], boolean>,
  'initializeProducts' : ActorMethod<[], undefined>,
  'initiateNagadPayment' : ActorMethod<[string, string], string>,
  'isBkashConfigured' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isNagadConfigured' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], undefined>,
  'removeFromCart' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveOrder' : ActorMethod<
    [string, Array<CartItem>, bigint, string, string],
    undefined
  >,
  'setBkashConfiguration' : ActorMethod<[BkashConfig], undefined>,
  'setNagadConfiguration' : ActorMethod<[NagadConfig], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateOrderStatus' : ActorMethod<[OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'uploadPrescription' : ActorMethod<
    [string, string, bigint, ExternalBlob],
    undefined
  >,
  'verifyNagadPayment' : ActorMethod<[string], string>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];